### ISSUE TITLE
SLDFC-2: Ignores job current directory

### ISSUE THREAD

**Issue by bruno-garcia** [stelynx/dart-full-coverage#6]
Does the action really need;

https://github.com/stelynx/dart-full-coverage/blob/7235b5bf519aa0b6077139277c4bfb46ffe0d659/src/executor.ts#L29

`cd $GITHUB_WORKSPACE`? This assumes the package is in the root. Why not let the thing run wherever the user of the action set the working dir to be?

**Comment by campovski** [comment]
@bruno-garcia Yes, you were right. When developing this action and for our needs, this was a sensible assumption, however it is a bit limiting. Please check the [PR](https://github.com/stelynx/dart-full-coverage/pull/7) to see is to solve your problems. Take a look at updated README.md to see the changes.

**Comment by bruno-garcia** [comment]
Thanks for your reply and PR

**Comment by campovski** [comment]
Closed by incomplete PR.

**Comment by campovski** [comment]
You are very welcome 😃
